name: Deploy
run-name: Deploy run name
on: pull_request
jobs:
  React-Testing-Library:
    runs-on: ubuntu-latest
    steps:
      - name: react testing library
        run: |
          npm run start
          npm run test