name: e2e test
run-name: e2e test
on: pull_request
jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: 사용할 코드 브랜치로 이동
        uses: actions/checkout@v4

      - name: 사용할 노드 버전 설치
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: install libraries
        run: npm install
        
      - name: run project
        run: npm run start

      - name: e2e test
        uses: cypress-io/github-action@v6
        with:
            browser: chrome
            cypress-start: npm run cypress
      